### ISSUE TITLE
Home Assistant 0.65(.4) fails to load module due to changed/removed module request_handler_factory

### ISSUE THREAD

**Issue by StevenLooman** [StevenLooman/home-assistant-dlna-dmr#4]
It appears that `homeassistant.components.http.request_handler_factory` has moved or is removed.

```
INFO:homeassistant.core:Bus:Handling <Event system_log_event[L]: timestamp=1521373204.0530322, level=ERROR, message=Error loading custom_components.media_player.dlna_dmr. Make sure all dependencies are installed, exception=Traceback (most recent call last):
  File "/home/steven/src/ha/home-assistant/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/home/steven/.virtualenvs/home-assistant/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/steven/.homeassistant/custom_components/media_player/dlna_dmr.py", line 17, in <module>
    from homeassistant.components.http import (
ImportError: cannot import name 'request_handler_factory'
, source=custom_components/media_player/dlna_dmr.py>

```

**Comment by StevenLooman** [comment]
It is moved to its own module: `homeassistant.components.http.view`.
